/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// CommandResponse struct for CommandResponse
type CommandResponse struct {
	Time time.Time `json:"time"`
	Message string `json:"message"`
	Success bool `json:"success"`
	ReplyToCommandRequestId string `json:"replyToCommandRequestId"`
	StreamName string `json:"streamName,omitempty"`
	StreamType string `json:"streamType,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	CanceledAt time.Time `json:"canceledAt,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
