/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// EventDistinctStreamTypes struct for EventDistinctStreamTypes
type EventDistinctStreamTypes struct {
	Items []string `json:"items"`
}
