/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// EventHistogram struct for EventHistogram
type EventHistogram struct {
	Counts []EventHistogramEntry `json:"counts"`
}
