/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceStreamFileTailConfiguration struct for DeviceStreamFileTailConfiguration
type DeviceStreamFileTailConfiguration struct {
	Type string `json:"type"`
	Filename string `json:"filename"`
	FileFormat string `json:"fileFormat,omitempty"`
	TimeKey string `json:"timeKey,omitempty"`
	TimeFormat string `json:"timeFormat,omitempty"`
	Regex string `json:"regex,omitempty"`
}
