/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// AlertCommand struct for AlertCommand
type AlertCommand struct {
	CommandTemplateId string `json:"commandTemplateId"`
	ParameterValue string `json:"parameterValue,omitempty"`
}
