/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// Label struct for Label
type Label struct {
	Value string `json:"value"`
	DisplayName string `json:"displayName,omitempty"`
}
