/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// FreeTeleopSettingsForm struct for FreeTeleopSettingsForm
type FreeTeleopSettingsForm struct {
	ImageTopic0 string `json:"imageTopic0,omitempty"`
	ImageTopic1 string `json:"imageTopic1,omitempty"`
	JoystickTopic0 string `json:"joystickTopic0,omitempty"`
	JoystickTopic1 string `json:"joystickTopic1,omitempty"`
	MapTopic string `json:"mapTopic,omitempty"`
	OdomTopic string `json:"odomTopic,omitempty"`
	PointCloudTopic string `json:"pointCloudTopic,omitempty"`
	WorldReferenceFrameId string `json:"worldReferenceFrameId,omitempty"`
	BooleanTopics []BooleanTopic `json:"booleanTopics,omitempty"`
}
