/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// CommandTemplateListResponse struct for CommandTemplateListResponse
type CommandTemplateListResponse struct {
	Items []CommandTemplate `json:"items"`
}
