/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// GoogleSpreadsheetInspection struct for GoogleSpreadsheetInspection
type GoogleSpreadsheetInspection struct {
	ParseUrlFailed bool `json:"parseUrlFailed,omitempty"`
	SpreadsheetGetFailed bool `json:"spreadsheetGetFailed,omitempty"`
	SheetFindFailed bool `json:"sheetFindFailed,omitempty"`
	SheetTitle string `json:"sheetTitle,omitempty"`
	ParseResult GoogleSheetParseResult `json:"parseResult,omitempty"`
}
