/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// GetLooksResponse struct for GetLooksResponse
type GetLooksResponse struct {
	Items []LookerLook `json:"items"`
}
