/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// CommandRequest struct for CommandRequest
type CommandRequest struct {
	Id string `json:"id"`
	Command string `json:"command"`
	Parameter CommandParameter `json:"parameter"`
	CreatedAt time.Time `json:"createdAt"`
}
