/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// RosTopic struct for RosTopic
type RosTopic struct {
	Name string `json:"name"`
	Type string `json:"type"`
}
