/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// SheetParameters struct for SheetParameters
type SheetParameters struct {
	Url string `json:"url,omitempty"`
	SpreadsheetId string `json:"spreadsheetId"`
	Range string `json:"range"`
}
