/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// BeginUploadResponse struct for BeginUploadResponse
type BeginUploadResponse struct {
	FileId string `json:"fileId"`
	UploadId string `json:"uploadId"`
	PartUrls []string `json:"partUrls"`
	PartSize int64 `json:"partSize"`
}
