/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// InspectSpreadsheetRequest struct for InspectSpreadsheetRequest
type InspectSpreadsheetRequest struct {
	SpreadsheetUrl string `json:"spreadsheetUrl"`
}
