/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceStreamHardwareConfiguration struct for DeviceStreamHardwareConfiguration
type DeviceStreamHardwareConfiguration struct {
	Type string `json:"type"`
	HwDescriptor string `json:"hwDescriptor"`
	Quality string `json:"quality"`
}
