/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// SlackInfo struct for SlackInfo
type SlackInfo struct {
	WebhookUrl string `json:"webhookUrl"`
	WebhookChannel string `json:"webhookChannel"`
	ConfigurationUrl string `json:"configurationUrl"`
	TeamId string `json:"teamId,omitempty"`
	Token string `json:"token,omitempty"`
}
