/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// DeviceCredentials struct for DeviceCredentials
type DeviceCredentials struct {
	AccessKeyId string `json:"accessKeyId"`
	SecretAccessKey string `json:"secretAccessKey"`
	SessionToken string `json:"sessionToken"`
	Expiration time.Time `json:"expiration"`
	S3Region string `json:"s3Region"`
	S3UploadBucket string `json:"s3UploadBucket"`
}
