/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// EventExportSheetRequest struct for EventExportSheetRequest
type EventExportSheetRequest struct {
	Filter EventFilter `json:"filter"`
	AppUrlOrigin string `json:"appUrlOrigin"`
}
