/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// BoardListResponse struct for BoardListResponse
type BoardListResponse struct {
	Items []Board `json:"items"`
}
