/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// GoogleStorageInfo struct for GoogleStorageInfo
type GoogleStorageInfo struct {
	CredentialsJsonKey string `json:"credentialsJsonKey"`
	GoogleStorageExport GoogleStorageExport `json:"googleStorageExport,omitempty"`
	OutputFormat string `json:"outputFormat,omitempty"`
}
