/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// GenerateAccessTokenResponse struct for GenerateAccessTokenResponse
type GenerateAccessTokenResponse struct {
	Authentication Authentication `json:"authentication"`
	Token string `json:"token"`
}
