/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceConfigurationParams struct for DeviceConfigurationParams
type DeviceConfigurationParams struct {
	Version int64 `json:"version"`
	Id string `json:"id"`
}
