/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceProvisioningRequest struct for DeviceProvisioningRequest
type DeviceProvisioningRequest struct {
	ProvisioningToken string `json:"provisioningToken"`
	PublicKey string `json:"publicKey"`
}
