/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// BitCondition struct for BitCondition
type BitCondition struct {
	Key string `json:"key"`
	True bool `json:"true"`
	False bool `json:"false"`
}
