/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceConfigurationDocument struct for DeviceConfigurationDocument
type DeviceConfigurationDocument struct {
	Tags map[string]string `json:"tags,omitempty"`
	Resources DeviceResourcesConfiguration `json:"resources,omitempty"`
	Telemetry DeviceTelemetryConfiguration `json:"telemetry,omitempty"`
	Application DeviceApplicationConfiguration `json:"application,omitempty"`
	Teleop DeviceTeleopConfiguration `json:"teleop,omitempty"`
	PortForwarding DevicePortForwardingConfiguration `json:"portForwarding,omitempty"`
}
