/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// ThresholdAlertCondition struct for ThresholdAlertCondition
type ThresholdAlertCondition struct {
	Type string `json:"type"`
	Operator string `json:"operator"`
	Value float32 `json:"value"`
}
