/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// Network struct for Network
type Network struct {
	Name string `json:"name,omitempty"`
	Ip4 string `json:"ip4,omitempty"`
}
