/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// TeleopViewConfiguration struct for TeleopViewConfiguration
type TeleopViewConfiguration struct {
	StreamName interface{} `json:"streamName,omitempty"`
}
