/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// TeleopJoystickConfiguration struct for TeleopJoystickConfiguration
type TeleopJoystickConfiguration struct {
	Position string `json:"position,omitempty"`
	X TeleopJoystickAxisConfiguration `json:"x,omitempty"`
	Y TeleopJoystickAxisConfiguration `json:"y,omitempty"`
}
