/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UserTeleopTwistRosTopicConfiguration struct for UserTeleopTwistRosTopicConfiguration
type UserTeleopTwistRosTopicConfiguration struct {
	Type string `json:"type"`
	Joystick JoystickConfiguration `json:"joystick"`
}
