/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// InterventionResponse struct for InterventionResponse
type InterventionResponse struct {
	InterventionType string `json:"interventionType"`
	Data interface{} `json:"data"`
	InterventionId string `json:"interventionId"`
	UserId string `json:"userId,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
