/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// LocationViewport struct for LocationViewport
type LocationViewport struct {
	Center Location `json:"center"`
	Zoom float32 `json:"zoom"`
}
