/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// DeviceConfiguration struct for DeviceConfiguration
type DeviceConfiguration struct {
	DeviceId string `json:"deviceId,omitempty"`
	Version int64 `json:"version,omitempty"`
	Document DeviceConfigurationDocument `json:"document"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
