/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// PartialDevice struct for PartialDevice
type PartialDevice struct {
	OrganizationId string `json:"organizationId,omitempty"`
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	PublicKey string `json:"publicKey,omitempty"`
	Scope ScopeFilter `json:"scope,omitempty"`
	DesiredAgentVersion *string `json:"desiredAgentVersion,omitempty"`
	DesiredConfigurationVersion *int64 `json:"desiredConfigurationVersion,omitempty"`
	State DeviceState `json:"state,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
