/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UpdatedEventTriggerRequest struct for UpdatedEventTriggerRequest
type UpdatedEventTriggerRequest struct {
	LastUpdated int64 `json:"lastUpdated"`
}
