/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// NumericCondition struct for NumericCondition
type NumericCondition struct {
	Label string `json:"label"`
	Threshold interface{} `json:"threshold,omitempty"`
}
