/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceResourcesConfiguration struct for DeviceResourcesConfiguration
type DeviceResourcesConfiguration struct {
	Disk DeviceDiskConfiguration `json:"disk,omitempty"`
	StreamThrottleHz *float32 `json:"streamThrottleHz,omitempty"`
}
