/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// PartialAnnotationTemplate struct for PartialAnnotationTemplate
type PartialAnnotationTemplate struct {
	OrganizationId string `json:"organizationId,omitempty"`
	Name string `json:"name,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	Description string `json:"description,omitempty"`
	Fields []AnnotationField `json:"fields,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	PublishToGoogleSpreadsheetUrl *string `json:"publishToGoogleSpreadsheetUrl,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
