/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// OnDemandStreamPresence struct for OnDemandStreamPresence
type OnDemandStreamPresence struct {
	StreamName string `json:"streamName"`
	Presence []OnDemandPresenceStreamItemGroup `json:"presence"`
}
