/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// Channel struct for Channel
type Channel struct {
	OrganizationId string `json:"organizationId,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Filter Filter `json:"filter"`
	Layout interface{} `json:"layout,omitempty"`
	Configuration []ViewConfiguration `json:"configuration,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
