/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// CaptureSession struct for CaptureSession
type CaptureSession struct {
	OrganizationId string `json:"organizationId,omitempty"`
	UserId string `json:"userId,omitempty"`
	DeviceId string `json:"deviceId"`
	Code string `json:"code,omitempty"`
	Expiration time.Time `json:"expiration,omitempty"`
	StreamName string `json:"streamName"`
	Tags map[string]string `json:"tags"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
