/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// StripeInfo struct for StripeInfo
type StripeInfo struct {
	CustomerId string `json:"customerId"`
	SubscriptionId string `json:"subscriptionId,omitempty"`
	Card StripeCard `json:"card,omitempty"`
	BillingAnchor interface{} `json:"billingAnchor,omitempty"`
}
