/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// BooleanTopic struct for BooleanTopic
type BooleanTopic struct {
	Topic string `json:"topic"`
	Mode string `json:"mode"`
}
