/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UserTeleopConfiguration struct for UserTeleopConfiguration
type UserTeleopConfiguration struct {
	RosStreams []UserTeleopRosStreamConfiguration `json:"rosStreams,omitempty"`
}
