/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UpdatedAgentVersionResponse struct for UpdatedAgentVersionResponse
type UpdatedAgentVersionResponse struct {
	DesiredAgentVersion string `json:"desiredAgentVersion,omitempty"`
}
