/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// FileInfo struct for FileInfo
type FileInfo struct {
	Id string `json:"id"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
}
