/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// TriggeredConfiguration struct for TriggeredConfiguration
type TriggeredConfiguration struct {
	ConfigurationDurationMinutes int64 `json:"configurationDurationMinutes"`
	ConfigurationTemplateId string `json:"configurationTemplateId"`
}
