/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// LookerInfo struct for LookerInfo
type LookerInfo struct {
	LookerGroupId int64 `json:"lookerGroupId"`
	LookerModels []string `json:"lookerModels"`
	LookerPermissions []string `json:"lookerPermissions"`
	LookerSpaceId float32 `json:"lookerSpaceId,omitempty"`
}
