/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// AudioDevice struct for AudioDevice
type AudioDevice struct {
	Id string `json:"id"`
	Name string `json:"name"`
}
