/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// JoystickConfiguration struct for JoystickConfiguration
type JoystickConfiguration struct {
	Linear string `json:"linear"`
	Angular string `json:"angular"`
	Scale float32 `json:"scale"`
	Sensitivity float32 `json:"sensitivity"`
}
