/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UsagePrices struct for UsagePrices
type UsagePrices struct {
	DataPoints float32 `json:"dataPoints"`
	Assets float32 `json:"assets"`
	Bytes float32 `json:"bytes"`
	Devices float32 `json:"devices"`
	RtcTurn float32 `json:"rtcTurn"`
	AdvancedConfiguration float32 `json:"advancedConfiguration"`
	Analytics float32 `json:"analytics"`
	CustomerPortal float32 `json:"customerPortal"`
	DataExport float32 `json:"dataExport"`
	DataRetention float32 `json:"dataRetention"`
	Support float32 `json:"support"`
	Teleop float32 `json:"teleop"`
	Observability float32 `json:"observability"`
	Share float32 `json:"share"`
	Mission float32 `json:"mission"`
	Diagnostics float32 `json:"diagnostics"`
	Ssh float32 `json:"ssh"`
	Spot float32 `json:"spot"`
}
