/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// PagerdutyInfo struct for PagerdutyInfo
type PagerdutyInfo struct {
	Account string `json:"account"`
	ServiceName string `json:"serviceName"`
	ServiceKey string `json:"serviceKey"`
}
