/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// Adapter struct for Adapter
type Adapter struct {
	OrganizationId string `json:"organizationId,omitempty"`
	Name string `json:"name"`
	FileId string `json:"fileId"`
	ExecCommand string `json:"execCommand"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
