/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceStreamRosTopicConfiguration struct for DeviceStreamRosTopicConfiguration
type DeviceStreamRosTopicConfiguration struct {
	Type string `json:"type"`
	Topic string `json:"topic"`
	Path string `json:"path,omitempty"`
	EncodeVideo bool `json:"encodeVideo,omitempty"`
}
