/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// KernelInfo struct for KernelInfo
type KernelInfo struct {
	Version string `json:"version,omitempty"`
	Release string `json:"release,omitempty"`
	Architecture string `json:"architecture,omitempty"`
}
