/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// GoogleLoginRequest struct for GoogleLoginRequest
type GoogleLoginRequest struct {
	Token string `json:"token"`
	AutoCreateOrg bool `json:"autoCreateOrg,omitempty"`
}
