/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UpdatedConfigurationQuery struct for UpdatedConfigurationQuery
type UpdatedConfigurationQuery struct {
	ReportedConfigurationVersion int64 `json:"reportedConfigurationVersion,omitempty"`
}
