/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// LocalizationViewConfiguration struct for LocalizationViewConfiguration
type LocalizationViewConfiguration struct {
	Camera Camera `json:"camera,omitempty"`
}
