/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// AwsInfo struct for AwsInfo
type AwsInfo struct {
	AccountId string `json:"accountId"`
	RoleName interface{} `json:"roleName"`
	S3Export S3Export `json:"s3Export,omitempty"`
	OutputFormat string `json:"outputFormat,omitempty"`
}
