/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// OnDemandPresenceTimeRange struct for OnDemandPresenceTimeRange
type OnDemandPresenceTimeRange struct {
	Start int64 `json:"start"`
	End int64 `json:"end"`
	ByteSize float32 `json:"byteSize"`
	ItemCount float32 `json:"itemCount"`
}
