/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// PartialDeviceLayout struct for PartialDeviceLayout
type PartialDeviceLayout struct {
	OrganizationId string `json:"organizationId,omitempty"`
	Name string `json:"name,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	Filter Filter `json:"filter,omitempty"`
	Layout interface{} `json:"layout,omitempty"`
	Configuration []ViewConfiguration `json:"configuration,omitempty"`
	Index int64 `json:"index,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
