/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// TriggeredConfiguration struct for TriggeredConfiguration
type TriggeredConfiguration struct {
	ConfigurationTemplateId string `json:"configurationTemplateId,omitempty"`
	StreamThrottleHz float32 `json:"streamThrottleHz,omitempty"`
	ConfigurationDurationMinutes int64 `json:"configurationDurationMinutes,omitempty"`
}
