/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// ImpersonateRequest struct for ImpersonateRequest
type ImpersonateRequest struct {
	UserId string `json:"userId"`
}
