/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// DeviceProvisioning struct for DeviceProvisioning
type DeviceProvisioning struct {
	DeviceId string `json:"deviceId,omitempty"`
	Token string `json:"token"`
	Expiration time.Time `json:"expiration"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
