/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// EventSort struct for EventSort
type EventSort struct {
	Column string `json:"column"`
	Order string `json:"order"`
}
