/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// TeleopJoystickAxisConfiguration struct for TeleopJoystickAxisConfiguration
type TeleopJoystickAxisConfiguration struct {
	Dimension string `json:"dimension,omitempty"`
	Scale float32 `json:"scale,omitempty"`
	Expo float32 `json:"expo,omitempty"`
	GamepadAxis int64 `json:"gamepadAxis,omitempty"`
}
