/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceDetailsListResponse struct for DeviceDetailsListResponse
type DeviceDetailsListResponse struct {
	Items []DeviceDetails `json:"items"`
}
