/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceRosConfiguration struct for DeviceRosConfiguration
type DeviceRosConfiguration struct {
	WorldReferenceFrameId string `json:"worldReferenceFrameId,omitempty"`
}
