/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// AnnotationFieldValue struct for AnnotationFieldValue
type AnnotationFieldValue struct {
	Key interface{} `json:"key"`
	Value interface{} `json:"value"`
	Tags map[string]string `json:"tags"`
}
