/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// LabeledPolygon struct for LabeledPolygon
type LabeledPolygon struct {
	Vertices [][]interface{} `json:"vertices"`
	Labels []string `json:"labels"`
}
