/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// SelectionRequestData struct for SelectionRequestData
type SelectionRequestData struct {
	Instruction string `json:"instruction"`
	ImageUrl string `json:"imageUrl"`
	Options []string `json:"options"`
	Hint int64 `json:"hint,omitempty"`
	Title string `json:"title,omitempty"`
}
