/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// AnnotationField struct for AnnotationField
type AnnotationField struct {
	Type string `json:"type"`
	Key interface{} `json:"key"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Required bool `json:"required"`
	Parameters interface{} `json:"parameters"`
}
