/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceTeleopRosStreamConfiguration struct for DeviceTeleopRosStreamConfiguration
type DeviceTeleopRosStreamConfiguration struct {
	TopicName string `json:"topicName"`
	TopicType string `json:"topicType"`
	Mode string `json:"mode"`
	EncodeVideo bool `json:"encodeVideo,omitempty"`
	StatusTopic string `json:"statusTopic,omitempty"`
	PlannedTopic string `json:"plannedTopic,omitempty"`
	EndEffectorTopic string `json:"endEffectorTopic,omitempty"`
	EndEffectorLinkName string `json:"endEffectorLinkName,omitempty"`
	PlanValidTopic string `json:"planValidTopic,omitempty"`
	AudioCodec string `json:"audioCodec,omitempty"`
	Min float32 `json:"min,omitempty"`
	Max float32 `json:"max,omitempty"`
	DefaultValue float32 `json:"defaultValue,omitempty"`
	Step float32 `json:"step,omitempty"`
	NumericControlVisualization string `json:"numericControlVisualization,omitempty"`
	Quality string `json:"quality,omitempty"`
}
