/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// DeviceQuery struct for DeviceQuery
type DeviceQuery struct {
	Name string `json:"name,omitempty"`
	Query string `json:"query,omitempty"`
	Tags interface{} `json:"tags,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Type string `json:"type,omitempty"`
	Count float32 `json:"count,omitempty"`
	Offset float32 `json:"offset,omitempty"`
	DisabledBefore time.Time `json:"disabledBefore,omitempty"`
}
