/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// Group struct for Group
type Group struct {
	OrganizationId string `json:"organizationId,omitempty"`
	Name string `json:"name"`
	TagKey interface{} `json:"tagKey"`
	TagValue interface{} `json:"tagValue"`
	Active bool `json:"active,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
