/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// BitsetViewConfiguration struct for BitsetViewConfiguration
type BitsetViewConfiguration struct {
	SplitByKey string `json:"splitByKey,omitempty"`
}
