/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// GoogleStorageExport struct for GoogleStorageExport
type GoogleStorageExport struct {
	Bucket string `json:"bucket"`
	Path string `json:"path,omitempty"`
}
