/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceListResponse struct for DeviceListResponse
type DeviceListResponse struct {
	Items []Device `json:"items"`
}
