/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// Challenge struct for Challenge
type Challenge struct {
	Type string `json:"type"`
	Session string `json:"session"`
	UserId string `json:"userId"`
	Email string `json:"email"`
}
