/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// NumericViewConfiguration struct for NumericViewConfiguration
type NumericViewConfiguration struct {
	Span int64 `json:"span,omitempty"`
	SplitByKey string `json:"splitByKey,omitempty"`
}
