/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// TagsResponse struct for TagsResponse
type TagsResponse struct {
	Tags interface{} `json:"tags"`
}
