/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// Camera struct for Camera
type Camera struct {
	Position Vector3 `json:"position"`
	Target Vector3 `json:"target"`
}
