/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// ThresholdEventTriggerCondition struct for ThresholdEventTriggerCondition
type ThresholdEventTriggerCondition struct {
	Type string `json:"type"`
	Operator string `json:"operator"`
	Value float32 `json:"value"`
}
