/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// AdminSignupRequest struct for AdminSignupRequest
type AdminSignupRequest struct {
	Email string `json:"email"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	OrganizationName string `json:"organizationName,omitempty"`
	OrganizationPlan string `json:"organizationPlan,omitempty"`
}
