/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UserTeleopRosStreamConfiguration struct for UserTeleopRosStreamConfiguration
type UserTeleopRosStreamConfiguration struct {
	TopicName string `json:"topicName"`
	DisplayName string `json:"displayName,omitempty"`
	Configuration interface{} `json:"configuration,omitempty"`
}
