/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// Authentication struct for Authentication
type Authentication struct {
	AccessToken string `json:"accessToken"`
	OrganizationId string `json:"organizationId"`
	UserId string `json:"userId"`
	RefreshToken string `json:"refreshToken,omitempty"`
	IsSuperuser bool `json:"isSuperuser,omitempty"`
}
