/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// VideoDevice struct for VideoDevice
type VideoDevice struct {
	Path string `json:"path"`
	Name string `json:"name"`
}
