/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceTeleopConfiguration struct for DeviceTeleopConfiguration
type DeviceTeleopConfiguration struct {
	RosStreams []DeviceTeleopRosStreamConfiguration `json:"rosStreams,omitempty"`
}
