/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// BeginUploadRequest struct for BeginUploadRequest
type BeginUploadRequest struct {
	FileName string `json:"fileName"`
	FileSize int64 `json:"fileSize"`
}
