/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceDiagnosticsConfiguration struct for DeviceDiagnosticsConfiguration
type DeviceDiagnosticsConfiguration struct {
	ReportLogs *bool `json:"reportLogs,omitempty"`
	ReportMetrics *bool `json:"reportMetrics,omitempty"`
}
