/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// Rectangle struct for Rectangle
type Rectangle struct {
	X int64 `json:"x"`
	Y int64 `json:"y"`
	Width int64 `json:"width"`
	Height int64 `json:"height"`
}
