/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UpdatedEventTriggerResponse struct for UpdatedEventTriggerResponse
type UpdatedEventTriggerResponse struct {
	EventTriggers *[]EventTrigger `json:"eventTriggers,omitempty"`
	LastUpdated int64 `json:"lastUpdated,omitempty"`
}
