/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// ViewConfiguration struct for ViewConfiguration
type ViewConfiguration struct {
	StreamName string `json:"streamName"`
	Type string `json:"type"`
	Configuration interface{} `json:"configuration"`
}
