/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// LookerLook struct for LookerLook
type LookerLook struct {
	Title string `json:"title"`
	Id int64 `json:"id"`
}
