/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// UuidListResponse struct for UuidListResponse
type UuidListResponse struct {
	Items []string `json:"items"`
}
