/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// ChannelListResponse struct for ChannelListResponse
type ChannelListResponse struct {
	Items []Channel `json:"items"`
}
