/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// PresenceEventTriggerCondition struct for PresenceEventTriggerCondition
type PresenceEventTriggerCondition struct {
	Type string `json:"type"`
}
