/*
 * Formant admin-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// RespondToNewPasswordRequiredChallengeRequest struct for RespondToNewPasswordRequiredChallengeRequest
type RespondToNewPasswordRequiredChallengeRequest struct {
	UserId string `json:"userId"`
	Session string `json:"session"`
	NewPassword string `json:"newPassword"`
}
