/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
// DeviceStreamRosLocalizationConfiguration struct for DeviceStreamRosLocalizationConfiguration
type DeviceStreamRosLocalizationConfiguration struct {
	Type string `json:"type"`
	OdomTopic string `json:"odomTopic"`
	MapTopic string `json:"mapTopic,omitempty"`
	PointCloudTopics []string `json:"pointCloudTopics,omitempty"`
	PathTopic string `json:"pathTopic,omitempty"`
	GoalTopic string `json:"goalTopic,omitempty"`
}
