/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin_api
import (
	"time"
)
// Share struct for Share
type Share struct {
	OrganizationId string `json:"organizationId,omitempty"`
	UserId string `json:"userId,omitempty"`
	Code string `json:"code,omitempty"`
	Scope ScopeFilter `json:"scope"`
	Time time.Time `json:"time"`
	Expiration time.Time `json:"expiration,omitempty"`
	Message string `json:"message,omitempty"`
	UserName string `json:"userName,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
