/*
 * Formant query-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// TelemetryExportSheetRequest struct for TelemetryExportSheetRequest
type TelemetryExportSheetRequest struct {
	Query Query `json:"query"`
}
