/*
 * Formant query-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// CountHistory struct for CountHistory
type CountHistory struct {
	Total int64 `json:"total"`
	Counts []CountHistoryEntry `json:"counts"`
}
