/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// MetadataListResponse struct for MetadataListResponse
type MetadataListResponse struct {
	Items []Metadata `json:"items"`
}
