/*
 * Formant query-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// StreamAggregateData struct for StreamAggregateData
type StreamAggregateData struct {
	Name string `json:"name"`
	DeviceId string `json:"deviceId"`
	Tags map[string]string `json:"tags"`
	Type string `json:"type"`
	Aggregates interface{} `json:"aggregates"`
}
