/*
 * Formant query-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// CountHistoryEntry struct for CountHistoryEntry
type CountHistoryEntry struct {
	Id string `json:"id"`
	Counts []CountHistoryEntryCount `json:"counts"`
}
