/*
 * Formant query-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// StringListResponse struct for StringListResponse
type StringListResponse struct {
	Items []string `json:"items"`
}
