/*
 * Formant Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package query_api
// CountHistory struct for CountHistory
type CountHistory struct {
	Counts []CountHistoryEntry `json:"counts"`
}
